config:
  time-between-actions: 40 #In ticks, the time between the plugin actions.
timezone:
  #Use the timezone where your server is hosted in.
  use-server-timezone: true
  #If above is false.
  timezone: America/Buenos_Aires #https://en.wikipedia.org/wiki/List_of_tz_database_time_zones Refer to TZ Identifier.
worlds: #List of worlds.
  1:
    #World name.
    world: world_nether
    #Backup folder name inside backups folder.
    backup: nether_backup
    prev_reset_commands: #commands to execute before the reset.
      - "[BROADCAST] &b&lHORIZON &bThe nether world is about to reset."
      - "[PLAYERS] spawn" # [PLAYERS] Will execute a command as all players in the world.
    after_reset_commands: #commands to execute after the reset.
      - ""
    warnings: 1h, 30m, 10m, 5m, 1m #warnings before the world reset.
    warnings_message: "&b&lHORIZON &bThe nether world is about to reset in $time."
    times:
      1: #1 (Monday) to 7 (Sunday).
        hour: 21:14 #24-hour format.
      3:
        hour: 18:05
      6:
        hour: 03:40
