config:
  debug-mode: false
  time-between-actions: 20 #In ticks, the time between the plugin actions.
  time-format: "&7%d &edays, &7%d &ehours, &7%d &eminutes, &7%d &eseconds"
  times-language:
    second: "&esecond"
    seconds: "&eseconds"
    minute: "&eminute"
    minutes: "&eminutes"
    hour: "&ehour"
    hours: "&ehours"
    day: "&eday"
    days: "&edays"
  reset_teleport:
    enable: true
    location: #Do not manually edit, set with /hr setTeleport

timezone:
  #Use the timezone where your server is hosted in.
  use-server-timezone: true
  #If above is false.
  timezone: America/Buenos_Aires #https://en.wikipedia.org/wiki/List_of_tz_database_time_zones Refer to TZ Identifier.
worlds: #List of worlds.
  1:
    #World name.
    world: world_nether
    #Backup folder name inside backups folder.
    backup: nether_backup
    #World environment.
    environment: NETHER #NORMAL, NETHER, THE_END
    prev_reset_commands: #commands to execute before the reset.
      - "[BROADCAST] &b&lHORIZON &bThe nether world is about to reset."
      - "[PLAYERS] spawn" # [PLAYERS] Will execute a command as all players inside the world.
    after_reset_commands: #commands to execute after the reset.
      - ""
    warnings: 1h, 30m, 10m, 5m, 1m, 10s, 5s, 4s, 3s, 2s, 1s #warnings before the world reset.
    warnings_message: "&b&lHORIZON &bThe nether world is about to reset in &e$time&b."
    times:
      1:
        expression: "5 0 * 8 *"
      2:
        expression: "5 0 * 8 *"
      3:
        expression: "5 0 * 8 *"
